package.json, pnpm-lock.yaml
corrige los paquetes vulnerables reportados por npm
=> update de paquetes

src/general-data-requests/getCustomer.ts, src/general-data-requests/schemas/customer.schema.ts, src/general-data-requests/types/getCustomer.interface.ts, src/general-data-requests/utils/querySearchCustomer.ts, src/general-data-requests/validateSearchCustomerParameters.ts, src/loan-requests/newLoan.ts, src/loan-requests/schemas/loanNew.schema.ts, src/loan-requests/schemas/propertiesForLoanRequest.schema.ts
-Se agrega id_agente como parámetro de búsqueda
-Se agregan validaciones sobre curp y esquemas
-Se agrega datos de aval del cliente
-Refactorización de código SQL
=> Mejoras en busqueda de clientes

src/user-service/login.ts, src/user-service/schemas/userSchema.ts, src/user-service/validateCredentials.ts
Pequeño refactor, porque tenia problemas de typescript y ademas no manejaba correctamente los diferentes escenarios de errores
=> refactor: manejando apropiadamente el proceso de login

src/loan-requests/loans/registerNewLoanRequest.ts
fix: moviendo bloque de codigo a try-chatch async
=> moviendo bloque de codigo a try-chatch async

src/validators/schemas/personaTelefono.schema.ts, src/validators/types/DatosBusqueda.interface.ts, src/validators/utils/querySearchData.ts, src/validators/validateCURP.ts, src/validators/validatePhones.ts, src/validators/validateSearchParameters.ts
Implementacion de validacion de teléfonos de avales y clientes
=> feat: Validacion de telefonos

src/validators/schemas/personaCURP.schema.ts, src/validators/types/DatosBusqueda.interface.ts, src/validators/utils/querySearchData.ts, src/validators/validateCURP.ts
Correciones sobre validacion de CURP y teléfonos de clientes y avales
Validaciones de Curp y teléfonos de avales devuelven id_aval en lugar de id
Esquema de CURP acepta id de avales y clientes
=> fix: correcciones sobre validacion de curp y telefonos

serverless.yml, src/loan-requests/viewRequestList.ts
Se agrego un nuevo endpoint con el boilerplate necesario para que funcione y regrese una respuesta generica
NA
NA
=> feat: nuevo endpoint de listado de solicitudes

src/validators/schemas/personaTelefono.schema.ts, src/validators/utils/querySearchData.ts
Validación de teléfonos ahora acepta una cadena vacía o nula o de longitud 0
=> Correcciones validador curp telefonos

serverless.yml, src/general-data-requests/getCustomer.ts, src/general-data-requests/getRequestDetail.ts, src/general-data-requests/schemas/request.schema.ts, src/general-data-requests/types/getRequest.interface.ts, src/general-data-requests/utils/querySearchRequestDetail.ts, src/general-data-requests/validateSearchRequestDetailParameters.ts
Implementación de endpoint para obtener el detalle de una registro de solicitud de préstamo
Fixes #29
=> Obtener detalle solicitud

serverless.yml, src/helpers/generateGetJsonResponse.ts, src/installments/installments.ts, src/installments/types/installments.type.ts
nuevo endpoint get de plazos (installments en ingles) para permitir obtener los diferentes plazos definidos en la tabla de plazo
Issue: #33 
NA
=> feat: endpoint de plazos

src/installments/installments.ts, src/installments/types/installments.type.ts, src/loan-requests/types/SPInsertNewLoanRequest.ts
habia un problema con el tipado que causaba problemas downstream en el proceso, asi que opte por obtener los campos en minusculas para evitar todos los problemas que daba en todo el flujo de la web y la posterior insercion de datos
NA
NA
=> fix: ajuste de tipos

src/loan-requests/schemas/loanList.schema.ts, src/loan-requests/types/loanRequest.ts, src/loan-requests/utils/querySearchLoanList.ts, src/loan-requests/viewLoanList.ts
Se agrego nueva logica para manejar los diferentes escenarios para ser incluidos en las clausulas where del query y poder hacer consultas mas precisas
NA
NA
=> feat: agregando clausulas where

src/general-data-requests/transactions/customer/registerNewCustomer.ts, src/loan-requests/loans/registerUpdateLoanRequest.ts, src/loan-requests/types/SPInsertNewLoanRequest.ts, src/loan-requests/utils/validateData.ts
Validaciones por roles usuario
-Ajuste para admitir cierre desde estatus ACTUALIZAR hasta RECHAZADO
-Ajuste para evitar que un usuario con rol de líder de grupo o cobrador cambie a estatus APROBADO una solicitud creada por él mismo
=> Validaciones por roles usuario

src/loan-requests/types/loanRequest.ts, src/loan-requests/utils/querySearchLoanList.ts, src/loan-requests/viewLoanList.ts
- Agregando un query nuevo para poder recuperar el listado de agentes de un grupo.
- Agregando condiciones para poder filtar por el id de agente.
NA
NA
=> Filtrado por agente

package.json, pnpm-lock.yaml
se ejecuto el audit y el outdated para poder actualizar los paquetes viejos y posiblemente peligrosos
NA
NA
=> chore: package audit and update

.husky/commit-msg, package.json, pnpm-lock.yaml, serverless.yml, src/customerFiles/getFile.ts, src/customerFiles/listFiles.ts, src/customerFiles/uploadFiles.ts
Correccion para lectura correcta de las variables de entorno que fueron cambiadas con el postfijo "MY_" para evitar colisiones con variables de entorno reservadas por AWS causando problemas con la resolución de credenciales
NA
=> fix: correccion en para .envs

serverless.yml, src/general-data-requests/getAddress.ts
Se implementa endpoint para realizar búsqueda de domicilios por medio del id
=> Búsqueda de dirección por id

src/validators/schemas/personaTelefono.schema.ts
las reglas de anyof estaban de mas en este endpoint, también los campos mandatorios fueron modificados para evitar mas errores
NA
NA
=> fix: corrijiendo schema

serverless.yml, src/general-data-requests/getAddress.ts, src/general-data-requests/getLoansRefinance.ts, src/helpers/table-schemas.ts
Implementación de búsqueda de préstamos candidatos a refinanciar por customerid
=> Búsqueda de prestamos candidatos a refinanciar

serverless.yml
- agregando el custom authorizer a endpoints que deberian de tenerlo ya que no deberian de tener acceso publico
- tambien se elimino el verbo del path para 2 endpoints dado que el request es el que dicta el tipo de peticion y no debe de formar parte del path
NA
NA
=> chore: adding authorizer

src/general-data-requests/getLoansRefinance.ts, src/general-data-requests/transactions/customer/updateCustomer.ts, src/general-data-requests/transactions/loan/registerNewLoan.ts, src/general-data-requests/transactions/refinancing/registerNewRefinancing.ts, src/general-data-requests/transactions/reporting/registerSnapshotRealInvestmentReport.ts, src/general-data-requests/utils/querySearchLoanToRefinance.ts, src/helpers/table-schemas.ts, src/loan-requests/loans/registerUpdateLoanRequest.ts, src/loan-requests/schemas/propertiesForLoanRequest.schema.ts, src/loan-requests/types/SPInsertNewLoanRequest.ts, src/loan-requests/utils/generateNewLoanRequestTable.ts, src/loan-requests/utils/validateData.ts
Implementación del proceso de refinanciamiento a partir de un requerimiento de préstamo aprobado
Fixes #59
=> Crear prestamo refinanciamiento

src/loan-requests/loans/registerUpdateLoanRequest.ts, src/loan-requests/updateLoan.ts, src/loan-requests/utils/validateData.ts, src/validators/schemas/personaCURP.schema.ts, src/validators/schemas/personaTelefono.schema.ts, src/validators/types/DatosBusqueda.interface.ts, src/validators/utils/querySearchData.ts, src/validators/validateCURP.ts, src/validators/validatePhones.ts
Mejora: Valida si el id de persona recibido tiene la misma curp/telefono y lo excluye de los resultados para evitar que el sistema detecte que ya existe aun cuando le pertenece al mismo id de persona.
Fix: Genera error al enviar id_cliente y id_loan_to_refinance con valores null o undefined
Fixes #62
=> feat: mejora endpoint curp y telefonos

src/loan-requests/schemas/propertiesForLoanRequest.schema.ts, src/loan-requests/utils/validateData.ts
Validaciones sobre:
1. iddomiclios de aval/cliente
2. CURP de aval/cliente
3. Teléfonos móvil/fijo de aval/cliente
Fixes #66
=> Mejora validar iddomicilios

src/general-data-requests/getLoansRefinance.ts, src/general-data-requests/transactions/refinancing/registerNewRefinancing.ts, src/general-data-requests/utils/querySearchLoanToRefinance.ts, src/loan-requests/utils/validateData.ts
Ajuste de query para búsqueda de préstamos candidatos a refinanciamiento
Se tenía hard-coded los préstamos con al menos 10 semanas ya pagadas, pero el dato de las semanas ya pagadas debe ser obtenido de la tabla PLAZOS
=> fix: arreglo en query de busqueda refinaciamiento

src/loan-requests/utils/querySearchLoanList.ts, src/loan-requests/viewLoanList.ts
Arreglo del query de filtrado de agentes
El menú contextual de filtrado por agente no muestra los nombres de los agentes
=> fix: filtro de listado de solicitudes de prestamo

serverless.yml, src/general-data-requests/getGuarantor.ts, src/general-data-requests/schemas/guarantor.schema.ts, src/general-data-requests/types/getGuarantor.interface.ts, src/general-data-requests/utils/querySearchGuarantor.ts
Implementación de endpoint para búsqueda de avales de forma independiente, actualmente cada cliente extraía el dato de su propio aval, ahora los avales pueden ser buscados independientemente.
=> feat: nuevo endpoint busqueda de avales

src/general-data-requests/utils/querySearchGuarantor.ts
Ahora se muestran únicamente avales sin clientes asignados
=> fix: ahora se muestran avales sin clientes asignados

src/general-data-requests/getLoansRefinance.ts, src/loan-requests/schemas/loanList.schema.ts, src/loan-requests/types/loanRequest.ts, src/loan-requests/utils/querySearchLoanList.ts
Eliminando 3 lineas del query final que se encargaba de la paginacion, ya no es necesario
NA
NA
=> fix: eliminando paginacion del query final
